package com.krt.home.testdrive.detail.bean

import com.alibaba.fastjson.annotation.JSONField

data class TestDriveDetailEntity(
        @JSONField(name = "practicability")
        val practicability: Int?,
        @JSONField(name = "bookNo")
        val bookNo: String?,
        @JSONField(name = "dlExp")
        val dlExp: Long?,
        @JSONField(name = "idCardNo")
        val idCardNo: String?,
        @JSONField(name = "soldBy")
        val soldBy: Int?,
        @JSONField(name = "customerSex")
        val customerSex: String?,
        @JSONField(name = "influenceBuy")
        val influenceBuy: Int?,
        @JSONField(name = "recommend")
        val recommend: Int?,
        @JSONField(name = "customerMobileNo")
        val customerMobileNo: String?,
        @JSONField(name = "interior")
        val interior: Int?,
        @JSONField(name = "dlIss")
        val dlIss: Long?,
        @JSONField(name = "passengerRoom")
        val passengerRoom: Int?,
        @JSONField(name = "safety")
        val safety: Int?,
        @JSONField(name = "powerSteering")
        val powerSteering: Int?,
        @JSONField(name = "testDriver")
        val testDriver: String?,
        @JSONField(name = "createdTime")
        val createdTime: Long?,
        @JSONField(name = "customerBirthday")
        val customerBirthday: Long?,
        @JSONField(name = "comfortDegree")
        val comfortDegree: Int?,
        @JSONField(name = "customerAddress")
        val customerAddress: String?,
        @JSONField(name = "pcNo")
        val pcNo: String?,
        @JSONField(name = "updatedTime")
        val updatedTime: Long?,
        @JSONField(name = "updatedBy")
        val updatedBy: Int?,
        @JSONField(name = "isCancel")
        val cancel: Int?,
        @JSONField(name = "dealerId")
        val dealerId: Int?,
        @JSONField(name = "photoAgreement")
        val photoAgreement: String?,
        @JSONField(name = "photoDlCopy")
        val photoDlCopy: String?,
        @JSONField(name = "photoIdCardFront")
        val photoIdCardFront: String?,
        @JSONField(name = "version")
        val version: Int?,
        @JSONField(name = "customerName")
        val customerName: String?,
        @JSONField(name = "companyId")
        val companyId: Int?,
        @JSONField(name = "appearance")
        val appearance: Int?,
        @JSONField(name = "soldByName")
        val soldByName: String?,
        @JSONField(name = "createdBy")
        val createdBy: Int?,
        @JSONField(name = "photoDlOriginal")
        val photoDlOriginal: String?,
        @JSONField(name = "photoIdCardBack")
        val photoIdCardBack: String?,
        @JSONField(name = "service")
        val service: Int?,
        @JSONField(name = "reservationType")
        val reservationType: String?,
        @JSONField(name = "comprehensive")
        val comprehensive: Int?,
        @JSONField(name = "status")
        val status: String?,
        @JSONField(name = "modelPlateNumber")
        val modelPlateNumber: String?,
        @JSONField(name = "testDrivingTime")
        val testDrivingTime: Long?,
        @JSONField(name = "evaluation")
        val evaluation: String?
)